server:
  port: 8989

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/course_registration_system
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA? ??? database? dialect ??
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL? ?? ?? ??
        "[user_sql_comments]": true     #SQL?? ? ?? ??
        "[highlight_sql]": true         #SQL? ??
        "[hbm2ddl.auto]": create
    open-in-view: false
    show-sql: true


